name: mpoctrl_env
channels:
    - anaconda
    - numba
    - pytorch
    - nvidia
    - conda-forge
    - defaults
dependencies:
    - cuda-cudart=12.4.127
    - cuda-cupti=12.4.127
    - cuda-libraries=12.4.1
    - cuda-nvrtc=12.4.127
    - cuda-nvtx=12.4.127
    - cuda-opencl=12.6.77
    - cuda-runtime=12.4.1
    - cuda-version=12.6
    - lightning=2.4.0
    - lightning-utilities=0.11.8
    - matplotlib=3.9.2
    - matplotlib-base=3.9.2
    - matplotlib-inline=0.1.7
    - numba=0.61.0rc1
    - numpy=1.26.4
    - numpy-base=1.26.4
    - pandas=2.2.3
    - pysnooper=1.2.1
    - python=3.12.7
    - python-dateutil=2.9.0post0
    - python-tzdata=2023.3
    - pytorch=2.5.0
    - pytorch-cuda=12.4
    - pytorch-lightning=2.4.0
    - pytorch-mutex=1.0
    - scikit-learn=1.5.1
    - scipy=1.14.1
    - torchaudio=2.5.0
    - torchmetrics=1.4.2
    - torchtriton=3.1.0
    - torchvision=0.20.0
    - tqdm=4.66.5
    - yaml=0.2.5
